# Generated by Django 4.0.4 on 2023-05-17 07:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assets_type', models.CharField(choices=[('server', '物理机'), ('vmser', '虚拟机'), ('switch', '交换机'), ('route', '路由器'), ('printer', '打印机'), ('scanner', '扫描仪'), ('firewall', '防火墙'), ('storage', '存储设备'), ('wifi', '无线设备')], default='server', max_length=100, verbose_name='资产类型')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='资产编号')),
                ('buy_time', models.DateField(blank=True, null=True, verbose_name='购买时间')),
                ('expire_date', models.DateField(blank=True, null=True, verbose_name='过保修期')),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True, verbose_name='制造商')),
                ('model', models.CharField(blank=True, max_length=100, null=True, verbose_name='资产型号')),
                ('mark', models.TextField(blank=True, null=True, verbose_name='资产标示')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '资产管理',
                'verbose_name_plural': '总资产表',
                'db_table': 'apulis_assets',
                'permissions': (('assets_read_assets', '读取资产权限'), ('assets_change_assets', '更改资产权限'), ('assets_add_assets', '添加资产权限'), ('assets_delete_assets', '删除资产权限'), ('assets_dumps_assets', '导出资产权限')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Group_Assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=32, verbose_name='组名')),
                ('group_desc', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='备注')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '资产管理',
                'verbose_name_plural': '项目组',
                'db_table': 'apulis_group_assets',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Idc_Assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idc_name', models.CharField(max_length=32, verbose_name='机房名称')),
                ('idc_bandwidth', models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='机房带宽')),
                ('idc_linkman', models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='联系人')),
                ('idc_phone', models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='联系电话')),
                ('idc_address', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='机房地址')),
                ('idc_network', models.TextField(blank=True, default='', null=True, verbose_name='IP地址段')),
                ('update_time', models.DateField(auto_now=True, null=True)),
                ('idc_operator', models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='运营商')),
                ('idc_desc', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='备注')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '资产管理',
                'verbose_name_plural': '机房资产表',
                'db_table': 'apulis_idc_assets',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Status_Assent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=32, verbose_name='状态名称')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '资产管理',
                'verbose_name_plural': '机架',
                'db_table': 'apulis_status_assets',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Server_Assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('hostname', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('passwd', models.CharField(blank=True, default='root', max_length=100, null=True)),
                ('sudo_passwd', models.CharField(blank=True, max_length=100, null=True)),
                ('userkey', models.CharField(choices=[('yes', '使用密钥登录'), ('no', '使用密码登录')], max_length=100)),
                ('port', models.DecimalField(decimal_places=0, default=22, max_digits=6)),
                ('cpu', models.SmallIntegerField(blank=True, null=True)),
                ('disk_total', models.IntegerField(blank=True, null=True)),
                ('ram_total', models.IntegerField(blank=True, null=True)),
                ('kernel', models.CharField(blank=True, max_length=100, null=True)),
                ('system', models.CharField(blank=True, max_length=100, null=True)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('assets', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assets.assets')),
            ],
            options={
                'verbose_name': '资产管理',
                'verbose_name_plural': '服务器资产表',
                'db_table': 'apulis_server_assets',
                'permissions': (('assets_read_server', '读取服务器资产权限'), ('assets_change_server', '更改服务器资产权限'), ('assets_add_server', '添加服务器资产权限'), ('assets_delete_server', '删除服务器资产权限'), ('assets_webssh_server', '登陆服务器资产权限')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Card_Assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('card_sum', models.CharField(blank=True, max_length=100, null=True)),
                ('ram_total', models.IntegerField(blank=True, null=True)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('assets_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assets.assets')),
            ],
            options={
                'verbose_name': '资产管理',
                'verbose_name_plural': 'ai卡资产表',
                'db_table': 'apulis_card_assets',
                'permissions': (('assets_read_card', '读取服务器资产权限'), ('assets_change_card', '更改服务器资产权限'), ('assets_add_card', '添加服务器资产权限'), ('assets_delete_card', '删除服务器资产权限'), ('assets_webssh_card', '登陆服务器资产权限')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Cabinet_Assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabinet_name', models.CharField(max_length=32, verbose_name='机架名称')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('idc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.idc_assets')),
            ],
            options={
                'verbose_name': '资产管理',
                'verbose_name_plural': '机架',
                'db_table': 'apulis_cabinet_assets',
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='assets',
            name='cabinet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.cabinet_assets'),
        ),
        migrations.AddField(
            model_name='assets',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.group_assets'),
        ),
        migrations.AddField(
            model_name='assets',
            name='idc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.idc_assets'),
        ),
        migrations.AddField(
            model_name='assets',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.status_assent'),
        ),
    ]
