# Generated by Django 4.0.4 on 2023-05-23 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='assets_type',
            field=models.CharField(choices=[('server', '物理机'), ('card', 'ai卡'), ('switch', '交换机'), ('route', '路由器'), ('printer', '打印机'), ('scanner', '扫描仪'), ('firewall', '防火墙'), ('storage', '存储设备'), ('wifi', '无线设备')], default='server', max_length=100, verbose_name='资产类型'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='cabinet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.cabinet_assets'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.group_assets'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='idc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.idc_assets'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.status_assent'),
        ),
        migrations.AlterField(
            model_name='cabinet_assets',
            name='idc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.idc_assets'),
        ),
        migrations.AlterField(
            model_name='card_assets',
            name='assets_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assets.assets'),
        ),
        migrations.AlterField(
            model_name='server_assets',
            name='assets',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assets.assets'),
        ),
    ]
